import typing

class Eq:
    def __eq__(self, /, other: Eq) -> typing.Any: ...
    def __ne__(self, /, other: Eq) -> typing.Any: ...
    def __new__(cls, /, value: int) -> None: ...

class EqDefaultNe:
    def __eq__(self, /, other: EqDefaultNe) -> typing.Any: ...
    def __new__(cls, /, value: int) -> None: ...

class EqDerived:
    def __eq__(self, /, other: EqDerived) -> typing.Any: ...
    def __ne__(self, /, other: EqDerived) -> typing.Any: ...
    def __new__(cls, /, value: int) -> None: ...

class Ordered:
    def __eq__(self, /, other: Ordered) -> typing.Any: ...
    def __ge__(self, /, other: Ordered) -> typing.Any: ...
    def __gt__(self, /, other: Ordered) -> typing.Any: ...
    def __le__(self, /, other: Ordered) -> typing.Any: ...
    def __lt__(self, /, other: Ordered) -> typing.Any: ...
    def __ne__(self, /, other: Ordered) -> typing.Any: ...
    def __new__(cls, /, value: int) -> None: ...

class OrderedDefaultNe:
    def __eq__(self, /, other: OrderedDefaultNe) -> typing.Any: ...
    def __ge__(self, /, other: OrderedDefaultNe) -> typing.Any: ...
    def __gt__(self, /, other: OrderedDefaultNe) -> typing.Any: ...
    def __le__(self, /, other: OrderedDefaultNe) -> typing.Any: ...
    def __lt__(self, /, other: OrderedDefaultNe) -> typing.Any: ...
    def __new__(cls, /, value: int) -> None: ...

class OrderedDerived:
    def __eq__(self, /, other: OrderedDerived) -> typing.Any: ...
    def __ge__(self, /, other: OrderedDerived) -> typing.Any: ...
    def __gt__(self, /, other: OrderedDerived) -> typing.Any: ...
    def __le__(self, /, other: OrderedDerived) -> typing.Any: ...
    def __lt__(self, /, other: OrderedDerived) -> typing.Any: ...
    def __ne__(self, /, other: OrderedDerived) -> typing.Any: ...
    def __new__(cls, /, value: int) -> None: ...

class OrderedRichCmp:
    def __eq__(self, /, other: OrderedRichCmp) -> typing.Any: ...
    def __ge__(self, /, other: OrderedRichCmp) -> typing.Any: ...
    def __gt__(self, /, other: OrderedRichCmp) -> typing.Any: ...
    def __le__(self, /, other: OrderedRichCmp) -> typing.Any: ...
    def __lt__(self, /, other: OrderedRichCmp) -> typing.Any: ...
    def __ne__(self, /, other: OrderedRichCmp) -> typing.Any: ...
    def __new__(cls, /, value: int) -> None: ...
