import typing
def args_kwargs(*args, **kwargs): ...
def none(): ...
def positional_only(a: typing.Any, /, b: typing.Any): ...
def simple(a: typing.Any, b: typing.Any | None = ..., *, c: typing.Any | None = ...): ...
def simple_args(a: typing.Any, b: typing.Any | None = ..., *args, c: typing.Any | None = ...): ...
def simple_args_kwargs(a: typing.Any, b: typing.Any | None = ..., *args, c: typing.Any | None = ..., **kwargs): ...
def simple_kwargs(a: typing.Any, b: typing.Any | None = ..., c: typing.Any | None = ..., **kwargs): ...
